[EN-2082][EN-2083][EN-2084][EN-2085][EN-2086] Add Luna Toolbox
lunalabsltd/Bridge pull request #33
Opened 2021-08-23 14:12 UTC by ilya-shablovsky

Add Luna Toolbox.
Current features:
- Build Bridge lib and update dependencies in Luna
- Manage Bridge build version

2021-08-24 05:32 UTC, MakeevAlexey requested changes

2021-08-24 05:32 UTC, MakeevAlexey commented on .gitignore
> +Luna Toolbox/node_modules
remove space:
LunaToolbox

2021-08-24 05:32 UTC, MakeevAlexey commented on Luna Toolbox/lib/cli.js
> +function getTask(options) {
apply code styles

2021-08-24 05:32 UTC, MakeevAlexey commented on Luna Toolbox/lib/defines.js
> +				path.join(this.lunaPath, 'pipeline/templates/LunaCompiler/Vendor/com.unity.ui/1.2.1/1.2.1.csproj'),
This pathes can change - we need to correctly handle that issue

2021-08-24 05:32 UTC, MakeevAlexey commented on Luna Toolbox/lib/jobs/build.js
> +function build(options, config) {
Please - write down in Confluence, how to extend your solution

2021-08-24 11:11 UTC, ilya-shablovsky commented on .gitignore
> +Luna Toolbox/node_modules
Done.

2021-08-24 11:12 UTC, MakeevAlexey commented on Luna Toolbox/lib/cli.js
> +function getTask(options) {
and actually enable linter for that

2021-08-24 13:30 UTC, ilya-shablovsky commented on Luna Toolbox/lib/defines.js
> +				path.join(this.lunaPath, 'pipeline/templates/LunaCompiler/Vendor/com.unity.ui/1.2.1/1.2.1.csproj'),
Just checked your concern, if any path is wrong - the utility will let you know with the message `No files match the pattern: [filepath]`

2021-08-24 14:28 UTC, ilya-shablovsky commented on Luna Toolbox/lib/jobs/build.js
> +function build(options, config) {
Done.
https://lunalabsltd.atlassian.net/l/c/B3YS4954

2021-08-24 15:16 UTC, ilya-shablovsky commented on Luna Toolbox/lib/cli.js
> +function getTask(options) {
Done.

2021-08-25 06:28 UTC, MakeevAlexey approved these changes

2021-08-25 09:12 UTC, merged