[EN-2087] Add bridge tests
lunalabsltd/Bridge pull request #35
Opened 2021-10-18 18:33 UTC by ilya-shablovsky

2021-10-19 06:15 UTC, MakeevAlexey requested changes
Also for the future of this tool, we need to add "man" command with all available commands and descriptions

2021-10-19 06:15 UTC, MakeevAlexey commented on Bridge/Bridge.csproj
> +    <Compile Include="System\IO\filestream.cs" />
Looks weird, why?

2021-10-19 06:15 UTC, MakeevAlexey commented on Bridge/Bridge.csproj
> +    <Content Include="Resources\.auxiliary\assemblyend.js" />
Please be consistent across all C#/JS filenames

2021-10-19 06:15 UTC, MakeevAlexey commented on Compiler/Translator/Utils/Roslyn/DiscardReplacer.cs
> +                        }
afaik, it was a bug on mac. please put a comment, that it's inconsistency of bridge behaviour on different platform(runtimes) with different. this is invalueable information

2021-10-19 06:15 UTC, MakeevAlexey commented on LunaToolbox/.eslintrc.js
> +    root: true,
i see linter but don't see linter task on CI, am i blind or just you just forgot?

2021-10-19 06:15 UTC, MakeevAlexey commented on LunaToolbox/lib/jobs/test.js
> +const puppeteer = require( 'puppeteer' );
As we plan to have different tools in our toolbox, please make a separatee hierarchy for bridge tools. for now filepath is not verbose

2021-10-19 06:15 UTC, MakeevAlexey commented on LunaToolbox/lib/jobs/config.js
> +        bridgePath: path.join( __dirname, '../../..' ),
is it ok for both OS?

2021-10-19 18:45 UTC, ilya-shablovsky commented on Compiler/Translator/Utils/Roslyn/DiscardReplacer.cs
> +                        }
Done.

2021-10-19 18:46 UTC, ilya-shablovsky commented on LunaToolbox/lib/jobs/config.js
> +        bridgePath: path.join( __dirname, '../../..' ),
In fact, this option is should be used only for CI

2021-10-19 22:02 UTC, ilya-shablovsky commented on Bridge/Bridge.csproj
> +    <Content Include="Resources\.auxiliary\assemblyend.js" />
Fixed.

2021-10-20 13:12 UTC, MakeevAlexey requested changes
check once again please, what can be gitignored (.generated)
And prepare it to QA

2021-10-20 13:12 UTC, MakeevAlexey commented on Tests/Runner/Batch2/Bridge.Test/bridge.clienttest.batch2.runner.js
> +                    this.context = ($t = new Bridge.Test.Runtime.FixtureContext(), $t.Project = "Batch2", $t.ClassName = "Bridge.ClientTest.Batch2.BridgeIssues.Bridge1385", $t.File = "file:///Users/i
cleanup personal pathes

2021-11-03 10:53 UTC, merged