[EN-1241] Expand AggregateException to provide meaningful info about error
lunalabsltd/Bridge pull request #48
Opened 2022-08-18 12:20 UTC by ilya-shablovsky

<img width="777" alt="image" src="https://user-images.githubusercontent.com/79448455/185393120-ff649fb4-82ce-44b3-8824-a310ff8ac4b1.png">

2022-08-18 14:41 UTC, vladimir-tikhonov approved these changes

2022-08-18 14:43 UTC, vladimir-tikhonov approved these changes

2022-08-19 05:58 UTC, zhemchugovstepan approved these changes

2022-08-19 11:18 UTC, Tokatak approved these changes

2022-08-19 11:22 UTC, MakeevAlexey requested changes
For now all bridge errors are shown as one projDiag message let's make them separate.
Also try to cut away as much unnecessary info as possible

2022-08-22 09:09 UTC, MakeevAlexey requested changes

2022-08-22 09:09 UTC, MakeevAlexey commented on Compiler/Builder/Program.cs
> +                    logger.Error(string.Format("Bridge.NET Compiler error: {0}", ex.Message));
```suggestion
                    logger.Error(string.Format("Bridge.NET Compiler error: \n{0}", ex.Message));
```

2022-08-22 09:09 UTC, MakeevAlexey commented on Compiler/Translator/Translator/Translator.InspectAssembly.cs
> +                    errors.Add("[ErrorMessage]" + fileName + ":" + error.Region.BeginLine + "," + error.Region.BeginColumn + ": " + error.Message);
please use $"", and put a space after "[ErrorMessage] "

2022-08-22 09:09 UTC, MakeevAlexey commented on Compiler/Translator/Translator/Translator.cs
> +                throw new Exception("Compilation Error! For details see errors above.", ex);
code styles

2022-08-22 13:50 UTC, ilya-shablovsky commented on Compiler/Translator/Translator/Translator.cs
> +                throw new Exception("Compilation Error! For details see errors above.", ex);
@MakeevAlexey means spaces inside paranthesis.
And Bridge code style is differs from Luna one's, so, there are no parenthesis spaces across the project.
We discussed it directly and decided to leave as is.

2022-08-22 13:50 UTC, ilya-shablovsky commented on Compiler/Translator/Translator/Translator.InspectAssembly.cs
> +                    errors.Add("[ErrorMessage]" + fileName + ":" + error.Region.BeginLine + "," + error.Region.BeginColumn + ": " + error.Message);
done

2022-08-22 13:50 UTC, ilya-shablovsky commented on Compiler/Builder/Program.cs
> +                    logger.Error(string.Format("Bridge.NET Compiler error: {0}", ex.Message));
done

2022-08-22 14:07 UTC, MakeevAlexey approved these changes

2022-08-22 14:46 UTC, merged