[EN-3414] Rework typemarkers
lunalabsltd/Bridge pull request #49
Opened 2022-12-14 17:01 UTC by ilya-shablovsky

Replace string typemarkers with numbers to improve speed of comparison

2022-12-26 08:55 UTC, vladimir-tikhonov requested changes

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/class.js
> +            const st = performance.now();
Please use `lunaStartup`, like here - https://github.com/lunalabsltd/integration/blob/develop/pipeline/templates/html/resources/pug/compress.pug#L164. There's no point in measuring performance in network builds

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/interfaces.js
> +        $kind: Bridge.Typemarkers.Interface
I'm pretty sure that this change breaks troll.js - https://github.com/lunalabsltd/troll/blob/master/src/js-parser/index.ts#L135

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/array.js
> +                if (!v || (!v.$kind  && typeof v !== "object")) {
nope

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/class.js
> +            // if (Math.floor(prop.$kind / Bridge.Typemarkers.NestedOffset) > 0) {
nope

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/class.js
> +            // var rNames = ["fields", "events", "props", "ctors", "methods"],
nope

2022-12-26 08:55 UTC, vladimir-tikhonov commented on Bridge/Resources/class.js
> +    // Bridge.define = Bridge.Class.define;
nope

2022-12-26 09:22 UTC, Tokatak requested changes

2022-12-26 09:22 UTC, Tokatak commented on Bridge/Resources/class.js
> +            // if (Math.floor(prop.$kind / Bridge.Typemarkers.NestedOffset) > 0) {
This looks like a meaningless commit

2022-12-26 09:22 UTC, Tokatak commented on Bridge/Resources/class.js
> +            // var rNames = ["fields", "events", "props", "ctors", "methods"],
This as well

2022-12-26 09:22 UTC, Tokatak commented on Bridge/Resources/class.js
> +    // Bridge.define = Bridge.Class.define;
Forgotten lines

2022-12-26 09:22 UTC, Tokatak commented on Compiler/Translator/Emitter/Blocks/AnonymousTypeCreateBlock.cs
> +            this.WriteScript((int)TypeKind.Anonymous + 1);
Why do we use +1 here ?

2022-12-26 09:22 UTC, Tokatak commented on Compiler/Translator/Emitter/Blocks/ClassBlock.cs
> +                kindMarker += 1000;
+= Bridge.Typemarkers.NestedOffset
?

2023-01-03 13:20 UTC, ilya-shablovsky commented on Compiler/Translator/Emitter/Blocks/AnonymousTypeCreateBlock.cs
> +            this.WriteScript((int)TypeKind.Anonymous + 1);
We need to have offset, to make typechecking easier in JS
Anyway, this shoud be moved to constants 👍

2023-01-03 13:20 UTC, ilya-shablovsky commented on Compiler/Translator/Emitter/Blocks/ClassBlock.cs
> +                kindMarker += 1000;
Done

2023-01-03 13:20 UTC, ilya-shablovsky commented on Bridge/Resources/interfaces.js
> +        $kind: Bridge.Typemarkers.Interface
Good point, you are absolutely right
Gonna update it too

2023-01-04 13:51 UTC, ilya-shablovsky commented on Bridge/Resources/interfaces.js
> +        $kind: Bridge.Typemarkers.Interface
Here is the PR for troll: https://github.com/lunalabsltd/troll/pull/26

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +            const st = performance.now();
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/array.js
> +                if (!v || (!v.$kind  && typeof v !== "object")) {
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +            // if (Math.floor(prop.$kind / Bridge.Typemarkers.NestedOffset) > 0) {
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +            // var rNames = ["fields", "events", "props", "ctors", "methods"],
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +    // Bridge.define = Bridge.Class.define;
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +            // if (Math.floor(prop.$kind / Bridge.Typemarkers.NestedOffset) > 0) {
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +            // var rNames = ["fields", "events", "props", "ctors", "methods"],
Removed

2023-01-05 11:38 UTC, ilya-shablovsky commented on Bridge/Resources/class.js
> +    // Bridge.define = Bridge.Class.define;
Removed

2023-01-05 14:48 UTC, vladimir-tikhonov approved these changes

2023-01-05 14:52 UTC, Tokatak commented
![image](https://user-images.githubusercontent.com/13577949/210808705-934328e8-f3a7-4488-a44d-969ce082374b.png)

2023-01-05 14:53 UTC, Tokatak approved these changes

2023-01-06 07:55 UTC, merged